### PR TITLE
Add @abroadunderhood and @elixirunderhood to list

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by iamstarkov** [comment]
do you know who is driving elexir’s account?

**Comment by davydovanton** [comment]
Yes
/cc @KernelMadness

**Comment by iamstarkov** [comment]
hey @KernelMadness, do you wanna website?

**Comment by davydovanton** [comment]
@iamstarkov what about merge my changes?

**Comment by iamstarkov** [comment]
@davydovanton done();

**Comment by davydovanton** [comment]
Nice, thanks @iamstarkov! :star2:

**Pull request merged**
