### PR TITLE
Add @iamreadingstuff to awesome list

### PR DESCRIPTION
**Pull request by davydovanton**
https://twitter.com/iamreadingstuff
:cake:

### CODE REVIEW

**Comment by iamstarkov** [comment]
is there any bourbon there?

**Comment by davydovanton** [comment]
I don't know ¯_(ツ)_/¯

**Comment by iamstarkov** [comment]
then maybe remove it?

**Comment by davydovanton** [comment]
okay.jpg

**Comment by davydovanton** [comment]
done :tada:

**Comment by davydovanton** [comment]
thanks! :+1:

**Pull request merged**
