### PR TITLE
New underhood twitters

### PR DESCRIPTION
**Pull request by ligurio**

### CODE REVIEW

**Comment by ligurio** [comment]
Please :)

**Comment by iamstarkov** [comment]
@ligurio Was not sure about them last week

**Comment by iamstarkov** [comment]
they are not collective at all

**Comment by ligurio** [comment]
Really? Previous week was a first week for both twitters.
@sorrowudnerhood:
previous week was driven by @strizhechenko (https://twitter.com/sorrowunderhood/status/719439958147260416)
and this week by  @errorsoul (https://twitter.com/sorrowunderhood/status/719446458429267968)

@kernelunderhood:
previous week was driven by @strizhechenko
this week we didn't found new author yet.

**Comment by iamstarkov** [comment]
so _kernelunderhood_ is dead

**Pull request closed without merging**
