### PR TITLE
cleanup abandoned accounts

### PR DESCRIPTION
**Pull request by iamstarkov**
@davydovanton pls take a look

### CODE REVIEW

**Comment by davydovanton** [comment]
yes, I agree with you :+1: 
@artemeff what do you know about elixirunderhood? Is it still alive?

**Comment by artemeff** [comment]
ping @kernelmadness

**Comment by KernelMadness** [comment]
It's alive! Elixirunderhood has no speakers :(
But, I have some plans.

**Comment by iamstarkov** [comment]
sorry,, if you have no authors, then project is dead, at least for now

**Comment by iamstarkov** [comment]
feel free to re-add your project, when you will need that

**Pull request merged**
